# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Rachel Abrahams'
tagline:          'test site'
description:      'description'
url:              
baseurl:          /portfolio/

author:
  name:           'Rachel Abrahams'
  url:            https://twitter.com/rachels_archive

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rachelabrahams/portfolio
